apiVersion: v1
kind: Secret
metadata:
  name: {{ include "city-manager.fullname" . }}
  labels:
    {{- include "city-manager.labels" . | nindent 4 }}
type: Opaque
data:
  ELASTIC_URL: "aHR0cDovL2VsYXN0aWNzZWFyY2gtbWFzdGVyOjkyMDA="
